// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/CommercialHomepage.tsx": () => import("../components/mockups/CommercialHomepage.tsx"),
  "./components/mockups/InsuranceCompliancePage.tsx": () => import("../components/mockups/InsuranceCompliancePage.tsx"),
  "./components/mockups/ResidentialHomepage.tsx": () => import("../components/mockups/ResidentialHomepage.tsx"),
  "./components/mockups/SiteOverview.tsx": () => import("../components/mockups/SiteOverview.tsx")
};
